var button1 = document.getElementById("button1");
var button2 = document.getElementById("button2");
var button3 = document.getElementById("button3");
var text = document.getElementById("text");

function show_image(src, width, height, alt) {
  var img = document.createElement("img");
  img.src = src;
  img.style.width = width + "px";
  img.style.height = height + "px";
  img.alt = alt;

  var container = document.createElement("div");
  container.style.display = "flex";
  container.style.justifyContent = "center";
  container.style.alignItems = "center";
  container.style.position = "absolute";
  container.style.top = "0";
  container.style.left = "0";
  container.style.bottom = "0";
  container.style.right = "0";
  container.appendChild(img);

  var menu = document.getElementsByClassName("menu");
  menu.appendChild(container);
}

button1.addEventListener("click", function() {
  displayText("IoT is the network of physical objects or groups of objects that are equipped with sensors, processing capabilities, software, and other technologies to connect and exchange information with other devices and systems via the internet or other communication networks ");
});

button2.addEventListener("click", function() {
  displayText("");
});

button3.addEventListener("click", function() {
  displayText("- IoT (Internet of Things) is the overarching concept that connects all the other components together.\n\n- Devices are the physical objects that are connected to the internet and communicate with other devices or services. Examples include smartphones, wearables, smart home appliances, industrial machinery, and more.\n\n- Sensors are devices that detect and measure physical phenomena like temperature, humidity, light, sound, and motion. They collect data and send it to other devices or services for processing and analysis.\n\n- Actuators are devices that can perform physical actions based on data received from sensors or other sources. Examples include motors, valves, and switches.\n\n- Smart Objects are devices that combine sensors, actuators, and some level of intelligence to perform specific tasks or provide useful information. Examples include smart thermostats, smart locks, and smart lighting systems.\n\n- Data Processing & Storage refers to the infrastructure and systems that collect, analyze, and store data generated by IoT devices. This can include edge computing devices, data centers, and cloud services.\n\n- Cloud Services are the platforms and services that enable IoT applications to run and interact with data. Examples include cloud computing platforms, data analytics services, and machine learning tools.\n\n- Applications are the end-user interfaces that allow people to interact with IoT devices and services. Examples include mobile apps, web dashboards, and voice assistants.");
});

function displayText(textToDisplay) {
  text.innerHTML = textToDisplay;
  text.style.display = "block";
}